package com.example.dnd.srd.model.enums;

public enum RacesEnum {
    Aasimar, Dragonborn, Dwarf, Elf, Gnome, Goliath, Halfling, Human, Orc, Tiefling,
    Dhampir, Hexblood, Lupin, Reborn,
    Boggart, Faerie, Flamekin, Kithkin, Lorwyn_Changeling, Lorwyn_Shadowmoor_Elf, Rimekin,
    Changeling, Kalashtar, Khoravar, Shifter, Warforged,
    Duskling, Aarakocra, Aasimar_L, Air_Genasi,
    Bugbear, Centaur, Changeling_L,
    Deep_Gnome, Duergar, Earth_Genasi, Eladrin, Fairy, Firbolg, Fire_Genasi, Githyanki,
    Githzerai, Goblin, Goliath_L, Harengon, Hobgoblin, Kenku, Kobold, Lizardfolk,
    Minotaur, Orc_L, Satyr, Sea_Elf, Shadar_kai, Shifter_L, Tabaxi, Tortle,
    Triton, Water_Genasi, Yuan_ti,
    Kender, Astral_Elf, Autognome, Giff, Hadozee, Plasmoid, Thri_kreen,
    Owlin, Dhampir_L, Hexblood_L, Reborn_L, Leonin, Satyr_L,
    Changeling_L2, Kalashtar_L, Shifter_L2, Warforged_L,
    Verdan, Centaur_L, Loxodon, Minotaur_L, Simic_Hybrid, Vedalken,
    Feral_Tiefling, Tortle_L, Locathah, Grung, Gith_L, Aasimar_L2, Bugbear_L, Firbolg_L,
    Goblin_L, Hobgoblin_L, Kenku_L, Kobold_L, Lizardfolk_L, Orc_L2, Tabaxi_L, Triton_L, Yuan_ti_Pureblood,
    Aarakocra_L, Genasi_L, Goliath_L2, Dragonborn_L, Dwarf_L, Elf_L, Gnome_L, Half_Elf_L,
    Halfling_L, Half_Orc, Human_L, Tiefling_L, Geppettin, Mandrake, Aasimar_E,
    Dhakaani_Ghaal_dar_H, Dhakaani_Golin_dar_G, Dhakaani_Guul_dar_B, Jhorgun_taal_HO,
    Kalamer_Landwalker_M, Ruinbound, Sahuagin,
    Alfar_HE, Baugsmidr_Dwarf, Bearfolk, Beastkin, Fjord_Dwarf, Giantkin, Ice_Elf, Trollkin, Werekin,
    Manikin, Scourgeborne, Floral_Dragonborn,
    Gargoyle, Gnoll, Harpy, Medusa, Tiefling_E, Worg,
    Bearfolk_E, Darakhul, Erina, Quickstep, Ratatosk, Ravenfolk, Satarre, Shade, Shadow_Goblin,
    Umbral_Human, The_Disembodied_L, Wechselkind_L, Dara, Elf_O, Nakudama,
    Cervan, Corvum, Gallus, Hedge, Jerbeen, Luma, Mapach, Raptor, Strig, Vulpin,
    Cnidaran, Cyclopian, Gobboc, Golynn, Rakin,
    Lotol, Mycelian, Ombrask, Oozekin, Opteran, Feathren,
    Ashborn, Azureborn, Bogborn, Curseborn, Deepborn, Gnarlborn, Graveborn,
    Harvestborn, Plagueborn, Relicborn, Silkborn, Stoneborn, Threadborn,
    Accursed, Arisen, Dhampir_G, Disembodied, Downcast, Dragonborn_G,
    Dreamer, Dwarf_G, Elf_G, Gnome_G, Grudgel,
    Halfling_G, Human_G, Laneshi, Ogresh, Wechselkind, Wulven,
    Canisar, Hederan, Snowborn, Tarandus,
    Barding, Dwarf_LOTR, Elf_LOTR, Hobbit, Man_of_Bree, Ranger_of_the_North,
    Etherean, Geleton, Ankylier, Jeholrak, Limukin, Pluvenn, The_Children_of_Seth, The_Manyhorn
}
